import static com.sun.org.apache.xalan.internal.lib.ExsltDatetime.dateTime;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.Timer;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Lenovo
 */
public class Journey_details extends javax.swing.JFrame {

    /**
     * Creates new form Journey_details
     */
    Connection conn;
    
    PreparedStatement ps;
    PreparedStatement p;
    public Journey_details() {
        initComponents();
        
       
    }

        String username;
        
     public Journey_details(String user) {
        initComponents();
        this.username=user;
        
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        journeyDetails_heading = new javax.swing.JLabel();
        from_dropdown = new javax.swing.JComboBox<>();
        to_dropdown = new javax.swing.JComboBox<>();
        ticket_type_Dropdown = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        generate_ticket_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 204, 255));

        jPanel2.setBackground(new java.awt.Color(51, 153, 255));

        journeyDetails_heading.setBackground(new java.awt.Color(51, 153, 255));
        journeyDetails_heading.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        journeyDetails_heading.setForeground(new java.awt.Color(255, 255, 255));
        journeyDetails_heading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        journeyDetails_heading.setText("Journey Details");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(journeyDetails_heading, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(257, 257, 257))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(journeyDetails_heading, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        from_dropdown.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        from_dropdown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Please Select", "Versova", "DN Nagar", "Azad Nagar", "Andheri", "Western Express Highway", "Chakala", "Airport Road", "Marol Naka ", "Saki Naka", "Asalpha", "Jagruti Nagar", "Ghatkopar" }));
        from_dropdown.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        from_dropdown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                from_dropdownActionPerformed(evt);
            }
        });

        to_dropdown.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        to_dropdown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Please Select", "Versova", "DN Nagar", "Azad Nagar", "Andheri", "Western Express Highway", "Chakala", "Airport Road", "Marol Naka ", "Saki Naka", "Asalpha", "Jagruti Nagar", "Ghatkopar" }));
        to_dropdown.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        to_dropdown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                to_dropdownActionPerformed(evt);
            }
        });

        ticket_type_Dropdown.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ticket_type_Dropdown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Please Select", "Single Journey", "Return Journey" }));
        ticket_type_Dropdown.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ticket_type_Dropdown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ticket_type_DropdownActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(102, 204, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("From");

        jLabel2.setBackground(new java.awt.Color(102, 204, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("To");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Ticket Type");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        generate_ticket_button.setBackground(new java.awt.Color(102, 204, 255));
        generate_ticket_button.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        generate_ticket_button.setText("Generate Ticket");
        generate_ticket_button.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        generate_ticket_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        generate_ticket_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generate_ticket_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(from_dropdown, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(to_dropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(generate_ticket_button, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)))
                .addGap(69, 69, 69)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ticket_type_Dropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(74, 74, 74))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(from_dropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ticket_type_Dropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(to_dropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(101, 101, 101)
                .addComponent(generate_ticket_button, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(117, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void generate_ticket_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generate_ticket_buttonActionPerformed
        String From=  from_dropdown.getSelectedItem().toString();
        String To= to_dropdown.getSelectedItem().toString();
        String Ticket_Type= ticket_type_Dropdown.getSelectedItem().toString();
        String User=username;
        String ticket_no=null;
        if(!From.equalsIgnoreCase("Please Select")&& !To.equalsIgnoreCase("Please Select" )&& !Ticket_Type.equalsIgnoreCase("Please Select"))
        {  if(!From.equals(To))
           {
               try{
               conn = DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/users?user=root&password=Chakra@321");
               ps =conn.prepareStatement("insert into journey (source,destination,ticket_type,email_id)values(?,?,?,?)  ");
             
               ps.setString(1,From);
               ps.setString(2,To);
               ps.setString(3, Ticket_Type);
               ps.setString(4,User);

               ps.executeUpdate();
                
                p=conn.prepareStatement("select ticket_no from journey where email_id like ?");
                p.setString(1,User);
                ResultSet rs=p.executeQuery();
                while(rs.next())
                {
                ticket_no=rs.getString("ticket_no");
                }
                
                
                
               Ticket_Page gnrTicket = new Ticket_Page(User);
               gnrTicket.source.setText(From);
               gnrTicket.ticket_no.setText(ticket_no);
               gnrTicket.destination.setText(To);
               gnrTicket.ticket_type.setText(Ticket_Type);
               gnrTicket.user_name.setText(User);
               gnrTicket.setVisible(true);
               gnrTicket.setLocationRelativeTo(null);
               this.dispose();
               }
               catch(SQLException ex)
               {
                    System.err.println(ex);
               }
            
           }
           
           else
           {
               JOptionPane.showMessageDialog(this,"From and To can't be same");
               
           }
           
        }
       
        
        
    }//GEN-LAST:event_generate_ticket_buttonActionPerformed

    private void from_dropdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_from_dropdownActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_from_dropdownActionPerformed

    private void to_dropdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_to_dropdownActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_to_dropdownActionPerformed

    private void ticket_type_DropdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ticket_type_DropdownActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ticket_type_DropdownActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Journey_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Journey_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Journey_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Journey_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Journey_details().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> from_dropdown;
    private javax.swing.JButton generate_ticket_button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel journeyDetails_heading;
    private javax.swing.JComboBox<String> ticket_type_Dropdown;
    private javax.swing.JComboBox<String> to_dropdown;
    // End of variables declaration//GEN-END:variables

    void getCusername(String user) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
