import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Lenovo
 */
public class LOGIN_PAGE extends javax.swing.JFrame {

    /**
     * Creates new form LOGIN_PAGE
     */
    Connection conn;
    PreparedStatement ps;
    public LOGIN_PAGE() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        login_page_heading = new javax.swing.JLabel();
        passfield_loginpage = new javax.swing.JPasswordField();
        username_field_loginpage = new javax.swing.JTextField();
        username_heading_loginpage = new javax.swing.JLabel();
        password_heading_loginpage = new javax.swing.JLabel();
        login_button_loginpage = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(102, 204, 255));

        jPanel4.setBackground(new java.awt.Color(51, 153, 255));

        login_page_heading.setBackground(new java.awt.Color(51, 153, 255));
        login_page_heading.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        login_page_heading.setForeground(new java.awt.Color(255, 255, 255));
        login_page_heading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        login_page_heading.setText("LOGIN");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(285, 285, 285)
                .addComponent(login_page_heading, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(304, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(login_page_heading, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        passfield_loginpage.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        username_field_loginpage.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        username_field_loginpage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                username_field_loginpageActionPerformed(evt);
            }
        });

        username_heading_loginpage.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        username_heading_loginpage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        username_heading_loginpage.setText("Username");

        password_heading_loginpage.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        password_heading_loginpage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        password_heading_loginpage.setText("Password");

        login_button_loginpage.setBackground(new java.awt.Color(102, 204, 255));
        login_button_loginpage.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        login_button_loginpage.setText("LOGIN");
        login_button_loginpage.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        login_button_loginpage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_button_loginpageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(328, 328, 328)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(username_heading_loginpage, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                            .addComponent(password_heading_loginpage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(303, 303, 303)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(passfield_loginpage, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(username_field_loginpage, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(login_button_loginpage, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(330, 330, 330))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(username_heading_loginpage)
                .addGap(14, 14, 14)
                .addComponent(username_field_loginpage, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(password_heading_loginpage)
                .addGap(18, 18, 18)
                .addComponent(passfield_loginpage, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(login_button_loginpage, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 99, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void login_button_loginpageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_button_loginpageActionPerformed
        // TODO add your handling code here:
        String user=username_field_loginpage.getText();
        String password=passfield_loginpage.getText();
        String passgot= null;
        if(!user.isEmpty()&& !password.isEmpty())
        {
        try{
           
            conn=DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/users?user=root&password=Chakra@321");
            ps=conn.prepareStatement("select password from users where email_id=?");
            ps.setString(1,user);
           
            ResultSet rs=ps.executeQuery();
        
            while(rs.next())
            {
                passgot=rs.getString("password");
            }
            
        }
        catch(SQLException ex)
        {
            Logger.getLogger(LOGIN_PAGE.class.getName()).log(Level.SEVERE, null, ex);
        }
        if(password.equals(passgot))
        {
        Journey_details log_button = new Journey_details();
        log_button.setVisible(true);
        log_button.setLocationRelativeTo(null);
        //log_button.getCusername(user);
        this.dispose();
        }
        else
        {
           login_button_loginpage.setVisible(true);
           JOptionPane.showMessageDialog(this,"Incorrect Username/Password","Error",JOptionPane.ERROR_MESSAGE);
        }
        }
        else
        {
            JOptionPane.showMessageDialog(this,"Fill All Details","Error",JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_login_button_loginpageActionPerformed
    
    private void username_field_loginpageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_username_field_loginpageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_username_field_loginpageActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LOGIN_PAGE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LOGIN_PAGE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LOGIN_PAGE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LOGIN_PAGE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LOGIN_PAGE().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton login_button_loginpage;
    private javax.swing.JLabel login_page_heading;
    private javax.swing.JPasswordField passfield_loginpage;
    private javax.swing.JLabel password_heading_loginpage;
    private javax.swing.JTextField username_field_loginpage;
    private javax.swing.JLabel username_heading_loginpage;
    // End of variables declaration//GEN-END:variables
}
